#remote_theme: jekyll/minima
remote_theme: "mmistakes/so-simple-theme@3.2.0"

skin: "/assets/css/skins/default.css"
locale: en-US
title: "Model documentation test site"
description: "This is a short description"
#baseurl: # the subpath of your site, e.g. "/blog"
#url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
#logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax:
  enable: true
  combo: tex-svg # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags: ams # "none", "ams" (default), "all"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

collections:
  models:
    output: true
#  permalink: /:collection/:basename

defaults:
  - scope:
      path: ""
      type: "models"
    values:
      layout: "model"

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

plugins:
  - jekyll-sitemap
  - jekyll-toc
