remote_theme: jekyll/minima
#remote_theme: "mmistakes/so-simple-theme@3.2.0"

collections:
  models:
    output: true
#  permalink: /:collection/:basename

defaults:
  - scope:
      path: ""
      type: "models"
    values:
      layout: "model"

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

plugins:
  - jekyll-sitemap
  - jekyll-toc
